// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jayebchfzizkcixayctx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpheWViY2hmeml6a2NpeGF5Y3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDQ1MzIsImV4cCI6MjA3MTUyMDUzMn0.FSCtoxazKz0LwBMpqZObJ7SuxpDWKWuYF2aqr8N8how";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});